### ISSUE TITLE
AddonManager: Cannot install addons (Windows related ?)

### ISSUE THREAD

**Issue by PerennialNovice** [FreeCAD/AddonManager#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

While trying to install an addon (tried different ones, does not seem specific) I always get an error

i.e. install SheetMetal Workbench

> Failed to install sheetmetal
> Git returned a non-zero exit status: 128
> Calles with: C:\cygwin\bin\git.EXE clone --recurse-submodules https://github.com/shaise/FreeCAD_SheetMetal C:\Users\User.Name\AppData\Roaming\FreeCAD\Mod\sheetmetal
> 
> Returned stderr:
> fatal: could not create work tree dir 'C:\Users\User.Name\AppData\Roaming\FreeCAD\Mod\sheetmetal': No such file or directory

But even before installing, there is an error output in the report view:

> 12:04:24  Invalid version specified for tag version in Addon Trails: 2022-01
> 12:04:26  An error occurred updating macros from GitHub, trying clean checkout...:
> Git returned a non-zero exit status: 128
> Called with: C:\cygwin\bin\git.EXE clone --recurse-submodules https://github.com/FreeCAD/FreeCAD-macros.git C:/Users/User.Name/AppData/Local/cache\FreeCAD\Cache\AddonManager\Macros
> 
> Returned stderr:
> Cloning into 'C:/Users/User.Name/AppData/Local/cache\FreeCAD\Cache\AddonManager\Macros'...
> fatal: unable to access 'https://github.com/FreeCAD/FreeCAD-macros.git/': error setting certificate verify locations:
>   CAfile: /etc/pki/tls/certs/ca-bundle.crt
>   CApath: none
> 
> 12:04:26  C:/Users/User.Name/AppData/Local/cache\FreeCAD\Cache\AddonManager\Macros
> 12:04:26  Attempting to do a clean checkout...
> 12:04:26  Traceback (most recent call last):
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_git.py", line 455, in _synchronous_call_git
> 12:04:26      proc = utils.run_interruptable_subprocess(final_args)
> 12:04:26             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_utilities.py", line 429, in run_interruptable_subprocess
> 12:04:26      raise subprocess.CalledProcessError(
> 12:04:26  subprocess.CalledProcessError: Command '['C:\\cygwin\\bin\\git.EXE', 'clone', '--recurse-submodules', 'https://github.com/FreeCAD/FreeCAD-macros.git', 'C:/Users/User.Name/AppData/Local/cache\\FreeCAD\\Cache\\AddonManager\\Macros']' returned non-zero exit status 128.
> 12:04:26  
> 12:04:26  The above exception was the direct cause of the following exception:
> 12:04:26  
> 12:04:26  Traceback (most recent call last):
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_workers_startup.py", line 339, in _update_local_git_repo
> 12:04:26      self.git_manager.clone(
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_git.py", line 90, in clone
> 12:04:26      self._synchronous_call_git(final_args)
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_git.py", line 457, in _synchronous_call_git
> 12:04:26      raise GitFailed(
> 12:04:26  addonmanager_git.GitFailed: Git returned a non-zero exit status: 128
> Called with: C:\cygwin\bin\git.EXE clone --recurse-submodules https://github.com/FreeCAD/FreeCAD-macros.git C:/Users/User.Name/AppData/Local/cache\FreeCAD\Cache\AddonManager\Macros
> 
> Returned stderr:
> Cloning into 'C:/Users/User.Name/AppData/Local/cache\FreeCAD\Cache\AddonManager\Macros'...
> fatal: unable to access 'https://github.com/FreeCAD/FreeCAD-macros.git/': error setting certificate verify locations:
>   CAfile: /etc/pki/tls/certs/ca-bundle.crt
>   CApath: none
> 12:04:26  
> 12:04:26  
> 12:04:26  During handling of the above exception, another exception occurred:
> 12:04:26  
> 12:04:26  Traceback (most recent call last):
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\bin\Lib\shutil.py", line 612, in _rmtree_unsafe
> 12:04:26      with os.scandir(path) as scandir_it:
> 12:04:26           ^^^^^^^^^^^^^^^^
> 12:04:26  FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/User.Name/AppData/Local/cache\\FreeCAD\\Cache\\AddonManager\\Macros'
> 12:04:26  
> 12:04:26  During handling of the above exception, another exception occurred:
> 12:04:26  
> 12:04:26  Traceback (most recent call last):
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_workers_startup.py", line 92, in run
> 12:04:26      self._retrieve_macros_from_git()
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_workers_startup.py", line 288, in _retrieve_macros_from_git
> 12:04:26      update_succeeded = self._update_local_git_repo()
> 12:04:26                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_workers_startup.py", line 359, in _update_local_git_repo
> 12:04:26      shutil.rmtree(macro_cache_location, onerror=self._remove_readonly)
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\bin\Lib\shutil.py", line 787, in rmtree
> 12:04:26      return _rmtree_unsafe(path, onerror)
> 12:04:26             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\bin\Lib\shutil.py", line 615, in _rmtree_unsafe
> 12:04:26      onerror(os.scandir, path, sys.exc_info())
> 12:04:26    File "C:\Program Files\FreeCAD 1.0\Mod\AddonManager\addonmanager_workers_startup.py", line 435, in _remove_readonly
> 12:04:26      os.chmod(path, stat.S_IWRITE)
> 12:04:26  FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/Users/User.Name/AppData/Local/cache\\FreeCAD\\Cache\\AddonManager\\Macros'
> 12:04:28  Invalid version specified for tag version in Addon Trails: 2022-01
> 12:04:30  Saved slider position at 0

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
I'm going to close this one a non-actionable since it seems like it was something screwy happening on the test system. If that proves not to be the case we can re-open.
